### ISSUE TITLE
Update the Readme file

### ISSUE THREAD

**Issue by Robinrai2612** [qaidjoharj53/Student-Management-System#1]
@qaidjoharj53  I'm excited to enhance your project's README for a friendlier and more welcoming experience. If you're onboard with this idea, I'll create a GitHub issue to get started. Thanks for considering this, and I'm eager to contribute!

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @Robinrai2612  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 , @rohitagr0310 , @jain-anshika .

**Comment by Robinrai2612** [comment]
Got it! @qaidjoharj53 Will work on the new branch named and request reviews from @qaidjoharj53, @rohitagr0310, and @jain-anshika when creating the pull request.

**Comment by Robinrai2612** [comment]
@qaidjoharj53 I am encountering an issue whenever I am trying to push it into the repository. I am receiving the following error.
remote: Permission to qaidjoharj53/Student-Management-System.git denied to Robinrai2612.
fatal: unable to access 'https://github.com/qaidjoharj53/Student-Management-System.git/': The requested URL returned error: 403

**Comment by Robinrai2612** [comment]
@qaidjoharj53 @rohitagr0310 @jain-anshika I have created a pull request. Please review it and let me know if any changes are required.
