### ISSUE TITLE
Convert whole CLI to GUI

### ISSUE THREAD

**Issue by qaidjoharj53** [qaidjoharj53/Student-Management-System#13]
Developers intereseted can comment and collaborate.

**Comment by divyansh-4** [comment]
Hi @qaidjoharj53 , could you please elaborate abit more on this. Are you looking for a Web app or something else. Maybe you could comment on the tech-stack that you would expect to be used which would make things easier to work on.

**Comment by qaidjoharj53** [comment]
@divyansh-4 
I want a GUI to be implemented using python's library PyQt.

**Comment by Kr-Adarsh** [comment]
Hi, I wish to contribute to this project. I hope this counts for the Hacktober fest 2024! if it's alright, Please assign it to me.
