### ISSUE TITLE
make the gui intuitive

### ISSUE THREAD

**Issue by qaidjoharj53** [qaidjoharj53/Student-Management-System#21]

**Comment by Kr-Adarsh** [comment]
Could you please give a little brief about what you mean by intuitive and what are the changes you're expecting?

**Comment by qaidjoharj53** [comment]
Hey @Kr-Adarsh 
Glad to see your attention towards this issue!

Clearing your doubts,
By intuitive, I mean the GUI should feel natural and easy to use, even for someone interacting with it for the first time. The layout should be simple, with clear navigation and minimal clicks to perform key actions. 
Make it interactive with 
- smooth transitions, 
- meaningful animations, 
- success/error messages, and 
- tooltips where needed. 
- It should also be responsive, adapting well across different screen sizes. 
Use a modern design with an appealing color palette, clear fonts, and eye-catching buttons to ensure it’s both functional and visually engaging.

Looking forward to review your PR completing and solving the issue #21

**Comment by Kr-Adarsh** [comment]
Thanks for clarifying @qaidjoharj53 , it's clear to me now.. I'll start working on it 👍

**Comment by Kr-Adarsh** [comment]
@qaidjoharj53 Sorry it took me a little longer than expected, as I had to learn a few things here and there 🥲. Anyways, please look at the new GUI and let me know if you need me to improve anything. #23 
Here's a demo video of it: 

https://github.com/user-attachments/assets/dba3f676-9d55-4509-92ce-07ca97f2fabb

To Run the New Gui: 
> python GUI_main.py

**Comment by qaidjoharj53** [comment]
@Kr-Adarsh As a beginner, you have did quite a good job!
But as this is our student management system, so the gui should look like professional.
Currently it has neon colours and somewhat gamified look, which is the thing to convert to professional look.

**Comment by Kr-Adarsh** [comment]
@qaidjoharj53 Thanks for your appreciation; as I mentioned, creating this type of GUI is very new to me, so I'm still figuring this out. I too, feel that it lacks a professional touch. But I'll try to understand and improve my understanding of color compositions and creating a somewhat aesthetic gui. By the way, feel free to personalize GUI via a `stylesheet.qss`.
