### ISSUE TITLE
Delete installation

### ISSUE THREAD

**Issue by k0msenapati** [qaidjoharj53/Student-Management-System#5]
![image](https://github.com/qaidjoharj53/Student-Management-System/assets/92045934/496b9c72-910f-4438-a161-65dca7685e5b)

Pickle module is used but the installation shows about mysql.

**Comment by rohitagr0310** [comment]
we wish to switch from pickel to mysql. but haven't been able to do so

**Comment by k0msenapati** [comment]
I could help

**Comment by k0msenapati** [comment]
I can start working on this if you assign me this issue.

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @kom-senapati 

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53
