### ISSUE TITLE
Dat file should be deleted

### ISSUE THREAD

**Issue by k0msenapati** [qaidjoharj53/Student-Management-System#6]
![image](https://github.com/qaidjoharj53/Student-Management-System/assets/92045934/35b33f6a-6eaa-48c1-8492-c97ba5c2f52d)

The .dat file should be deleted and a separate script could be added to create and add some fake data for the .dat file.

**Comment by rohitagr0310** [comment]
@kom-senapati how do you propose we do that

**Comment by qaidjoharj53** [comment]
@kom-senapati Can you please elaborate it.

As of my knowledge, There is 5 rows of data already inserted in stud.dat file.

**Comment by k0msenapati** [comment]
We don't need that .dat file, if a user needs it, he/she can generate it using a separate script that created the .dat file and some fake data using Faker.

**Comment by k0msenapati** [comment]
> @kom-senapati Can you please elaborate it.
> 
> As of my knowledge, There is 5 rows of data already inserted in stud.dat file.

If someone just needs the project why would he\she want this data?

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @kom-senapati  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 , @rohitagr0310 , @jain-anshika .
